
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
